apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: rabbit-mq-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: rabbit-mq-front
        image: ashwilliams/front-mq:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: RabbitApi
          value: "rabbit-mq-api"